# gpu number to use
gpu: 0

# model config
model: ResNetSE34V2
n_mels: 64
encoder_type: ASP
log_input: true
eval_frames: 0
initial_model: checkpoint/baseline_v2_ap.model

# path config
test_path: ./data/cod310/LibriSpeech_dataset/test_clean/wav
test_list: ./datas/librispeech_veri_test.txt
