import socketserver
import http.server
import logging
import cgi
import random
import time

import os

PORT = 8080

class ServerHandler(http.server.SimpleHTTPRequestHandler):

    def do_GET(self):
        logging.error(self.headers)
        http.server.SimpleHTTPRequestHandler.do_GET(self)

    def do_POST(self):
        logging.error(self.headers)

        form = cgi.FieldStorage(
            fp=self.rfile,
            headers=self.headers,
            environ={'REQUEST_METHOD':'POST',
                     'CONTENT_TYPE':self.headers['Content-Type'],
                     })

        # for item in form.list:
        #     logging.error(item)

        http.server.SimpleHTTPRequestHandler.do_GET(self)
        
        random.seed(time.time())
        print("----------------------\n")
        
        NUM_APPENDED = str(random.random())[2:7]
        NUM_APPENDED = ""
        
        FILENAME = "./uploads/" + NUM_APPENDED + str(form.list[0].filename)
        
        bytes = form.getvalue('filename')
        f = open(FILENAME, "wb")
        f.write(bytes)
        f.close()
        
        num = str(form.list[0].filename)
        num = ((num.split("_")[-1]).split(".")[0])
        num = num[3:]
        
        if "spectrogram_step_2" in FILENAME:
            os.system(f"sudo python3 spectrogram.py {num}")
            os.system(f"sudo python3 png_to_gif.py {num}")
            
        # with open("data.txt", "w") as file:
        #     for key in form.keys():
        #         file.write(str(form.getvalue(str(key))) + ",")

Handler = ServerHandler

httpd = socketserver.TCPServer(("", PORT), Handler)

print("serving at port", PORT)
httpd.serve_forever()


# Commands
# ngrok http 8080 (Need to have upload.php in the same folder)
# sudo python3 server.py
# curl -F "filename=@OutputFile.extenstion" http://10a7-103-40-199-45.ngrok.io/f (Link generated by ngrok)